### ISSUE TITLE
How to use it in desktop application?

### ISSUE THREAD

**Issue by waliarubal** [merken/Prise#1]
I have a .NET core 2.2 based Avalonia desktop application in which I want to use your framework. Let me know how shall I use your framework. Below is my current code for loading.

```
IServiceScope RegisterServices()
        {
            var collection = new ServiceCollection();

            var assemblies = AppDomain.CurrentDomain.GetAssemblies();
            foreach (var assembly in assemblies)
            {
                if (!assembly.FullName.StartsWith("Jaya", StringComparison.InvariantCultureIgnoreCase))
                    continue;

                var types = assembly.DefinedTypes;
                foreach (TypeInfo typeInfo in types)
                    if (typeInfo.IsClass && typeInfo.Name.EndsWith("Service", StringComparison.InvariantCulture))
                        collection.AddScoped(typeInfo);
            }

            var container = collection.BuildServiceProvider();
            var scopeFactory = container.GetRequiredService<IServiceScopeFactory>();
            return scopeFactory.CreateScope();
        }
```

**Comment by merken** [comment]
Hi, thanks for your interest in Prise.
I have a Azure functions example in the pipeline for this, and will be looking into creating an Avalon plugin as well. Can you be more specific about what exactly your plugin does ?

**Comment by waliarubal** [comment]
Mine is a very complex desktop application. It relies on several services (providers or plugins; whatever you want to call) which I would like to hold in different assemblies and load them dynamically. You can see my app [here](https://github.com/waliarubal/Jaya).

**Comment by merken** [comment]
I see.
I've been looking into it, you can follow the progress here : https://github.com/merken/Jaya/commits?author=merken

**Comment by waliarubal** [comment]
Thanks, nice work. Much appreciated.
I have also started using MEF to see if its easier in my current commits.

**Comment by waliarubal** [comment]
**Closing issue** for now since it no more appears to be a valid scenario for me. Thanks mate!

**Comment by merken** [comment]
For reference, please see complete working example at https://github.com/merken/Prise/tree/master/examples/AvaloniaAppWithPlugin
