### ISSUE TITLE
Is it planned to add documentation on how to use the Framework?

### ISSUE THREAD

**Issue by gigios** [merken/Prise#22]
Hi, I'm starting on using the framework to try to manage a my library as a plugin.
I have downloaded all the samples to check how works the framework, but it's not easy, for me, without knowing the architecture.
For example is not clear how manage the 'compatibility' with older plugins.
My idea is to have a base contract with the version of the plugin, but I'm not sure if this is the correct way to allow the compatibility from older and newer plugins.

For this reason I'm asking if it's planned to write a wiki or a documentation on the framework.

Thanks

**Comment by merken** [comment]
Hi,

Thanks for your question.
Currently, we're getting ready for .NET 5, documentation will come after that.

You will find more working examples at https://github.com/merken/prise.examples
Sorry for the delay.

**Comment by merken** [comment]
Hi,
Documentation is finally ready: https://merken.github.io/Prise/
