### ISSUE TITLE
System.Text.Json.JsonException when using a plug-in interface with async Task

### ISSUE THREAD

**Issue by snowbirder** [merken/Prise#33]
When creating a plug-in contract using an async method that just returns a Task, I get this exception when trying to call the plug-in through Prise:
```
System.Text.Json.JsonException: 'A possible object cycle was detected which is not supported. This can either be due to a cycle or if the object depth is larger than the maximum allowed depth of 0.'
```
It's quite easy is to replicate:
```
    public interface IMyPlugin
    {
        public Task TestAsync();
    }

    [Plugin(PluginType = typeof(IMyPlugin))]
    public class MyPlugin: IMyPlugin
    {
        public async Task TestAsync()
        {
            await Task.Run(() => Console.WriteLine("Inside of plug-in.")).ConfigureAwait(false);
        }
    }

```
On the host side, just call:
```
await plugin.TestAsync().ConfigureAwait(false);
```
and you get the exception above.

If you change the return to `Task<string>` or something else, it seems to work fine.

**Comment by merken** [comment]
Hi,

Returning a void (like an untyped Task) is not supported at the moment, the Prise.Proxy library needs updating in order to fix this.
Expect this to be fixed in the next release (.NET 5)

**Comment by snowbirder** [comment]
Thanks 👍

**Comment by merken** [comment]
Hi @snowbirder ,

Please check out Prise 2.0.0, support for the **Task return type** was added (among other things).

**Comment by snowbirder** [comment]
Thanks @merken
