### ISSUE TITLE
Contract ui

### ISSUE THREAD

**Issue by TartanLeGrand** [merken/Prise#43]
Hello,

I wanted to know if it was simple to make a contract for plugins to access UI components, from the application.

**Comment by merken** [comment]
Hi Thanks for reaching out.
Sorry for the delay.

PR 44 was created: https://github.com/merken/Prise/pull/44

This will include an example using an Avalonia cross platform UI app.

Hope this helps...

**Comment by TartanLeGrand** [comment]
Thank you for these precisions, it is really useful!

**Comment by merken** [comment]
You will need a newer version: 2.1.1

This version is now building... should be about 30mins before go-live
