### ISSUE TITLE
Invoke Plugin Publish command from Post Build Events

### ISSUE THREAD

**Issue by avatejo** [merken/Prise#46]
I need to call Prise plugin publish command from the Project Post Build Events.

I will jump into research to find out how to do it, but I f you can post example or instructions will be great.

Thanks for this useful code !

**Comment by merken** [comment]
Please check out the extensions for Vs code and visual studio :

https://marketplace.visualstudio.com/items?itemName=MRKN.PrisePublishPluginExtension

https://marketplace.visualstudio.com/items?itemName=MRKN.prise-publishpluginextension
