### ISSUE TITLE
Possibility to make plugins singletons?

### ISSUE THREAD

**Issue by mrukas** [merken/Prise#5]
Is there any possibility to add plugins as a singleton instance? For example if a plugin wants to keep some state over the time of its execution. It seems that the whole design is currently focused on creating a plugin instance per scope.

**Comment by merken** [comment]
Hi,
This depends on what your scope of the execution is, Prise is mainly designed to be used within ASP.NET Core applications, in a RESTful configuration.

You could inject a singleton service into your plugin, containing global state.

Do you have a concrete use-case, perhaps ?

**Comment by mrukas** [comment]
I want to extend an ASP.NET Core web application with plugins. But in my case the web application shouldn't rely on the plugins to be available. The code is written so that the plugins are optional. It should work like the plugin system for wordpress for example.
Furthermore i add own endpoints through plugins via "Application Parts" and my plugins should be able to register their own services via dependency injection  and use existing services that get provided by DI. To register own services in plugins i use "Hosting startup assemblies". Because of this reasons i implemented my plugins as singletons and provide hooks like "OnUserCreated" functions that plugins can override.

I'm currently using [DotNetCorePlugins](https://github.com/natemcmaster/DotNetCorePlugins) and it works. I'm just trying to ask myself if this is also possible with your solution, but I saw that you are loading the DLLs on demand and I'm not quite sure if this would be working with [hosted startup assemblies](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/platform-specific-configuration?view=aspnetcore-3.1) or [application parts](https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/app-parts?view=aspnetcore-3.1).

It would be awesome if you could share your thoughts about this topic.

**Comment by merken** [comment]
Hi,

This sounds like an ambitious project. On the topic of persistence, a plugin can have its own way of retrieving and storing data. I'll finish the samples by tonight.

**Comment by merken** [comment]
Docs and samples have been updated https://github.com/merken/Prise/blob/master/GettingStarted.md

**Comment by merken** [comment]
@mrukas Can we discuss this is via chat perhaps ? I have some questions regarding your architecture...

**Comment by mrukas** [comment]
@merken Thanks for updating the docs. Yeah of course. How would you like to chat? I'm currently at work but maybe in the evening?

**Comment by merken** [comment]
@mrukas please email me at merken.maarten@gmail.com
