### ISSUE TITLE
Question: Plugins from parallel projects (on solution)

### ISSUE THREAD

**Issue by ruilvo** [merken/Prise#51]
Hello there!

From what I understand you need to have plugins in a specific directory for the system to work. From the tutorial:

> We will publish the OpenWeather.Plugin to the _dist folder created at the root of our project, which means that the WeatherForecastController needs to look for Plugins from that directory on the local disk.

If I have a solution with several projects, one of them being the host, and another being a plugin, can I make it work without copying files? I mean, just by clicking "play" in Visual Studio without manual steps? Maybe with project references? 

Can this be made? 
Thanks

**Comment by merken** [comment]
Hi,

Please have a look at the extensions for VS Code and Visual Studio : https://merken.github.io/Prise/#/?id=%f0%9f%9a%80-toolset

Hope that helps you out with managing your solution.

Kr,
Maarten
