### ISSUE TITLE
services.AddPrise() middleware seems to be missing in latest .net 6 version release

### ISSUE THREAD

**Issue by hedronn** [merken/Prise#61]
Not sure if i am missing something. I am trying to update a 3.1 core project to .net 6 that using the Prise plugin framework. We have upgraded the nuget package to Prise 6.0.0 and the service.AddPrise() middleware method is no longer available. Is there any new documentation on migrating from .net core 3.1 to .net 6 for the Prise nuget package?

**Comment by merken** [comment]
Hi,

The namespaces have changed, please import Prise.DependencyInjection:
using Prise.DependencyInjection;

You might want to catch up on documentation: https://merken.github.io/Prise/#/
