### ISSUE TITLE
FindPlugin Problem

### ISSUE THREAD

**Issue by EugeneSu0515** [merken/Prise#63]
Why don't use PluginTypeName for FindPlugin?

My Situation is there have several implementation plugins within same assembly, so I can't use FindPlugin method to find specific plugin for execute.

I wish that assign PluginTypeName with implementation Type name and FindPlugin method can be implemented find by PluginTypeName as below.

`PluginTypeName = implementation.Name,` in ` public virtual Task<IEnumerable<AssemblyScanResult>> Scan(IAssemblyScannerOptions options)`

wish be  `.FirstOrDefault(p => p.PluginTypeName == plugin);`   or not `.FirstOrDefault(p => p.AssemblyPath.Split(Path.DirectorySeparatorChar).Last().Equals(plugin));` in `FindPlugin` implementation

How about with my recommendation? I wish it can be change in new version. Thanks.

**Comment by merken** [comment]
Hi Eugene,

Would you please provide a concrete example (repository) so that I can investigate?

Thanks!

**Comment by EugeneSu0515** [comment]
I realize that I can implement own AssemblyScanner and PluginLoader and inject my own implements when AddFactory.

So this issue can be resolve by above solution, thanks.

> Hi Eugene,
> 
> Would you please provide a concrete example (repository) so that I can investigate?
> 
> Thanks!
