### ISSUE TITLE
Getting started urls are dead

### ISSUE THREAD

**Issue by ferryferry** [merken/Prise#7]
Hi,
The URLS on the getting started page are all not found...
Just wanted to check the implementation since i'm developing a application which needs a plugin based architecture.

**Comment by ferryferry** [comment]
I've found the examples in another branch :) But maybe it's good to change the url paths

**Comment by merken** [comment]
Hi,
I'm migrating the examples to a different repo to focus on testing.

Please look here for the examples https://github.com/merken/Prise.Examples

**Comment by merken** [comment]
Docs have been updated. https://github.com/merken/Prise.Examples/tree/master/AssemblyDiscovery
